spring.application.name=Bank-Management-System

spring.datasource.url=jdbc:sqlite:Bank_management.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
management.endpoints.web.exposure.include=health
spring.jpa.show-sql= true

